sudo: required
os: linux
language: minimal
git:
  depth: 4
services:
  - docker

before_install:
  - docker pull openjdk:11-jre-slim

script:
  - docker version
  - docker build --no-cache --tag lacledeslan/gamesvr-minecraft:latest --tag lacledeslan/gamesvr-minecraft:1.14.4 --build-arg BUILDNODE=TravisCI --build-arg SOURCE_COMMIT="$TRAVIS_COMMIT" -f ./linux.Dockerfile .
  - docker run -it --rm lacledeslan/gamesvr-minecraft:latest ./ll-tests/gamesvr-minecraft.sh

notifications:
  slack:
    secure: Umz9YQrerCoCNQC/PiZkjQ5KMHjQgHOXAXsuWY27chd1jrIynzAxzYIOISiJTbkNeT48Og6WNy2VNexQ9rZGBZYPokVQzoBZJ7sI/oAuUb61j7LWDUMtLIExoXUp2SNj6IlnHvyZauixy0LlwH7w8grjDIdP1h5DXJTvi1PCGrox1A55mpGOYBryFC2PPdiCGyVnClFuQUVdHmGAP0j0MDmIctsnzqFv/mBx33YhFRhzBFtUyvzOKl8XGEISsrnNZU2RFUdDZdkUhYGeVJMTXVU5ktXGdye/et6GGxX3CMGPi9rYddTjfDg4rrbP+RVQnb5CGexCYoKzKkSiFFnHGKVQgKgmleg5Y3fU549dI/IseubXfv4E6RkvXrqs9z77MHM/gn7mYMnp0jOyhCwVbxyxyqOMGn2xRj61d3xVWdwNMaEDiK7zPrCGUIq+Wy8WdH/4eSy+gybZuHnrOR2TSXTpY3iXCgfpG2ezblsr6zDdhX0AUpuzdabaRcw+UqbmxOZalrAaAh1MMt4mTZn5C+KGkep/6un72TMC6gSE2jdtHCpblLLSdwYJ3vx2AzIcjISJit3P2QMY8ePuw+81cQD2ONZhOYU2w6VKCUzWw8tLfjU3JRNPTBCo8I6E1sP7NLCIlQg/eSxnSmw6jTOnFyWwSq4CjMQBpVCswYpuAAc=

before_deploy:
  - echo "$DOCKERHUB_PASS" | docker login -u "$DOCKERHUB_USER" --password-stdin;
deploy:
  - provider: script
    script: docker push lacledeslan/gamesvr-minecraft:latest
    on:
      branch: master
  - provider: script
    script: docker push lacledeslan/gamesvr-minecraft:1.14.4
    on:
      branch: master
after_deploy:
  - curl -X POST https://hooks.microbadger.com/images/lacledeslan/gamesvr-minecraft/$MICROBADGER_TOKEN
